#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# Copyright (C) 2020 LeapLu <https://www.ito.fun>
#
# <https://github.com/P3TERX/Actions-OpenWrt> 
# <https://github.com/KFERMercer/OpenWrt-CI>
# <https://github.com/leaplu/autoOpenWrt>
#

name: ASUS RT-N16

on:
  push:
    branches: 
      - master
  schedule:
    - cron: 0 */12 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -yqq update
          sudo -E apt-get -yqq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
      - name: Download lede
        run: |
          git clone https://github.com/coolsnowwolf/lede
          mv ./lede/* ./
      - name: Install addons
        run: |
          echo "src-git helloworld https://github.com/fw876/helloworld" >> ./feeds.conf.default 
          cd package
          mkdir openwrt-packages
          cd openwrt-packages
          git clone https://github.com/honwen/luci-app-aliddns.git
      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Costom configure file
        run: |
          sed -i 's/luci-theme-bootstrap/luci-theme-argon/g' feeds/luci/collections/luci/Makefile
          rm -f ./.config*
          touch ./.config
          cat >> .config <<EOF
          # Device type
          CONFIG_TARGET_bcm63xx=y
          CONFIG_TARGET_bcm63xx_mips74k=y
          CONFIG_TARGET_bcm63xx_mips74k_DEVICE_Alcatel RG100A=y

          # Gzip
          CONFIG_TARGET_IMAGES_GZIP=y

          # IPv6
          CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
          CONFIG_PACKAGE_ipv6helper=y

          # USB support
          ONFIG_PACKAGE_kmod-usb-core=y
          CONFIG_PACKAGE_kmod-usb-ohci=y
          CONFIG_PACKAGE_kmod-usb-ohci-pci=y
          CONFIG_PACKAGE_kmod-usb2=y
          CONFIG_PACKAGE_kmod-usb2-pci=y
          # CONFIG_PACKAGE_kmod-usb3 is not set
          # CONFIG_PACKAGE_kmod-usb-net=y
          # CONFIG_PACKAGE_kmod-usb-printer=y

          # APP
          # CONFIG_PACKAGE_luci-app-aliddns is not set
          CONFIG_PACKAGE_luci-app-frpc=y
          CONFIG_PACKAGE_luci-app-frps=y
          CONFIG_PACKAGE_luci-app-hd-idle=y
          CONFIG_DEFAULT_luci-app-music-remote-center=y
          CONFIG_PACKAGE_luci-app-mwan3=y
          CONFIG_PACKAGE_luci-app-mwan3helper=y
          CONFIG_PACKAGE_luci-app-openvpn=y
          CONFIG_PACKAGE_luci-app-openvpn-server=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Kcptun=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Server=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Socks=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Simple_obfs=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Trojan=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray_plugin=y
          CONFIG_PACKAGE_luci-app-syncdial=y
          CONFIG_PACKAGE_luci-app-ttyd=y
          CONFIG_PACKAGE_luci-app-usb-printer=y
          CONFIG_PACKAGE_luci-app-unblockneteasemusic-mini=y
          CONFIG_PACKAGE_luci-app-xlnetacc=y

          # APP lang
          CONFIG_PACKAGE_luci-i18n-hd-idle-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-mwan3-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-mwan3helper-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-openvpn-server-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-openvpn-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-usb-printer-zh-cn=y

          # Network adapter
          CONFIG_PACKAGE_kmod-mt7601u=y
          CONFIG_PACKAGE_kmod-rtl8192cu=y
          CONFIG_PACKAGE_kmod-rtl8xxxu=y
          CONFIG_PACKAGE_kmod-usb-net-rtl8152=y


          
          # frp
          # CONFIG_PACKAGE_frp=y
          
          EOF
          
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig
      - name: Download package source code
        run: |
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
      - name: Compile firmware
        run: |
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s
      - name : Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt firmware
          path: bin/targets
