#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# Copyright (C) 2020 LemoFire <https://www.ito.fun>
#
# <https://github.com/P3TERX/Actions-OpenWrt> 
# <https://github.com/KFERMercer/OpenWrt-CI>
# <https://github.com/LemoFire/autoOpenWrt>
#

name: PSG1218

on:
  push:
    branches: 
      - master
  schedule:
    - cron: 0 */12 * * *
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update -yqq
          sudo apt full-upgrade -yqq
          sudo apt install -yqq ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
      - name: Download lede
        run: |
          git clone https://github.com/coolsnowwolf/lede
          mv ./lede/* ./
      - name: Install addons
        run: |
          echo "src-git helloworld https://github.com/fw876/helloworld" >> ./feeds.conf.default 
          git clone https://github.com/kiddin9/openwrt-packages.git
          cd package
          mkdir openwrt-packages
          mv ../openwrt-packages/luci-app-aliddns openwrt-packages/luci-app-aliddns
          mv ../openwrt-packages/luci-app-eqos openwrt-packages/luci-app-eqos
          mv ../openwrt-packages/luci-app-wolplus openwrt-packages/luci-app-wolplus
          cd lean
          rm -rf luci-theme-argon  
          git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git  
      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Costom configure file
        run: |
          sed -i 's/luci-theme-bootstrap/luci-theme-argon/g' feeds/luci/collections/luci/Makefile
          # sed -i 's/country=US/country=CN/g' package/kernel/mac80211/files/lib/wifi/mac80211.sh
          rm -f ./.config*
          touch ./.config
          cat >> .config <<EOF
          # Device type
          CONFIG_TARGET_ramips=y
          CONFIG_TARGET_ramips_mt7620=y
          CONFIG_TARGET_ramips_mt7620_DEVICE_phicomm_psg1218a=y
          # CONFIG_TARGET_ramips_mt7620_DEVICE_phicomm_k2-v22.4=y
          CONFIG_TARGET_IMAGES_GZIP=y

          CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
          CONFIG_PACKAGE_ipv6helper=y

          # CONFIG_PACKAGE_busybox=n
          # CONFIG_PACKAGE_ca-certificates=n
          CONFIG_PACKAGE_curl=n
          CONFIG_PACKAGE_ddns-scripts=n
          CONFIG_PACKAGE_ddns-scripts_aliyun=n
          CONFIG_PACKAGE_ddns-scripts_dnspod=n
          # 114.5 kB
          CONFIG_PACKAGE_dropbear=n
          # CONFIG_PACKAGE_logd=n
          # 59.4 kB
          CONFIG_PACKAGE_opkg=n
          # CONFIG_PACKAGE_swconfig=n
          # CONFIG_PACKAGE_luci-app-accesscontrol=n
          # CONFIG_PACKAGE_luci-app-autoreboot=n
          # CONFIG_PACKAGE_luci-app-arpbind=n
          CONFIG_PACKAGE_luci-app-ddns=n
          CONFIG_PACKAGE_luci-app-filetransfer=n
          CONFIG_PACKAGE_luci-app-nlbwmon=n
          CONFIG_PACKAGE_luci-app-vsftpd=n
          CONFIG_PACKAGE_luci-app-vlmcsd=n
          CONFIG_PACKAGE_luci-app-wol=n

          CONFIG_PACKAGE_luci-app-turboacc=y
          CONFIG_PACKAGE_luci-app-turboacc_INCLUDE_SHORTCUT_FE_CM=y
          CONFIG_PACKAGE_luci-app-turboacc_INCLUDE_BBR_CCA=y
          CONFIG_PACKAGE_luci-app-turboacc_INCLUDE_PDNSD=n
          CONFIG_PACKAGE_luci-app-upnp=y
          CONFIG_PACKAGE_luci-app-eqos=y
          CONFIG_PACKAGE_luci-app-easymesh=y
          CONFIG_PACKAGE_luci-app-mwan3=y
          CONFIG_PACKAGE_luci-app-mwan3helper=y
          CONFIG_PACKAGE_luci-app-syncdial=y

          
          EOF
          
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig
      - name: Download package source code
        run: |
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
      - name: Compile firmware
        run: |
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s
      - name : Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt-PSG1218
          path: bin/targets/ramips/mt7620/openwrt-ramips-mt7620-phicomm_psg1218a-squashfs-sysupgrade.bin
