#
# This is free software, lisence use MIT.
#
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# Copyright (C) 2020 LemoFire <https://www.ito.fun>
#
# <https://github.com/P3TERX/Actions-OpenWrt>
# <https://github.com/KFERMercer/OpenWrt-CI>
# <https://github.com/LemoFire/autoOpenWrt>
#

name: R5C

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 */12 * * *
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update -yqq
          sudo apt full-upgrade -yqq
          sudo apt install -yqq ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
      - name: Download lede
        run: |
          git clone https://github.com/coolsnowwolf/lede
          mv ./lede/* ./
      - name: Install addons
        run: |
          # echo "src-git helloworld https://github.com/fw876/helloworld" >> ./feeds.conf.default 
          git clone https://github.com/kiddin9/openwrt-packages.git
          cd package
          mkdir openwrt-packages
          mv ../openwrt-packages/luci-app-aliddns openwrt-packages/luci-app-aliddns
          mv ../openwrt-packages/luci-app-eqos openwrt-packages/luci-app-eqos
          mv ../openwrt-packages/luci-app-wolplus openwrt-packages/luci-app-wolplus
          git clone https://github.com/sirpdboy/luci-app-ddns-go
          git clone --depth 1 -b luci https://github.com/xiaorouji/openwrt-passwall luci-app-passwall
          git clone --depth 1 -b packages https://github.com/xiaorouji/openwrt-passwall openwrt-passwall
      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Costom configure file
        run: |
          sed -i 's/luci-theme-bootstrap/luci-theme-argon/g' feeds/luci/collections/luci/Makefile
          # sed -i 's/country=US/country=CN/g' package/kernel/mac80211/files/lib/wifi/mac80211.sh
          rm -f ./.config*
          touch ./.config
          cat >> .config <<EOF
          # Device type
          CONFIG_TARGET_rockchip=y
          CONFIG_TARGET_rockchip_armv8=y
          CONFIG_TARGET_rockchip_armv8_DEVICE_friendlyarm_nanopi-r5c=y
          CONFIG_TARGET_KERNEL_PARTSIZE=100
          CONFIG_TARGET_ROOTFS_PARTSIZE=1800

          # IPv6
          # CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
          CONFIG_PACKAGE_ipv6helper=y

          # Storage
          # CONFIG_PACKAGE_autosamba=y


          # APP
          # CONFIG_PACKAGE_luci-app-aria2=y
          CONFIG_PACKAGE_luci-app-ddns=n
          CONFIG_PACKAGE_luci-app-ddns-go=y
          CONFIG_PACKAGE_luci-app-diskman=y
          # CONFIG_PACKAGE_luci-app-dockerman=y
          # CONFIG_PACKAGE_luci-app-frpc=y
          # CONFIG_PACKAGE_luci-app-frps=y
          # CONFIG_PACKAGE_luci-app-hd-idle=y
          # CONFIG_PACKAGE_luci-app-mwan3=y
          # CONFIG_PACKAGE_luci-app-mwan3helper=y
          # CONFIG_PACKAGE_luci-app-openvpn=y
          # CONFIG_PACKAGE_luci-app-openvpn-server=y
          # CONFIG_PACKAGE_luci-app-qos=y
          # CONFIG_PACKAGE_luci-app-syncdial=y
          CONFIG_PACKAGE_luci-app-ttyd=y
          # CONFIG_PACKAGE_luci-app-turboacc=y
          # CONFIG_PACKAGE_luci-app-usb-printer=y
          # CONFIG_PACKAGE_luci-app-upnp=y
          # CONFIG_PACKAGE_luci-app-vlmcsd=y
          # CONFIG_PACKAGE_luci-app-wrtbwmon=y
          # CONFIG_PACKAGE_luci-app-xlnetacc=y
          # CONFIG_PACKAGE_luci-app-zerotier=y

          # Third party packages
          # CONFIG_PACKAGE_luci-app-aliddns=y
          # CONFIG_PACKAGE_luci-app-eqos=y
          CONFIG_PACKAGE_luci-app-passwall=y
          CONFIG_PACKAGE_luci-app-wol=n
          CONFIG_PACKAGE_luci-app-wolplus=y
          
          # WLAN
          CONFIG_PACKAGE_wpad-openssl=y
          CONFIG_PACKAGE_mt7922bt-firmware=y
          CONFIG_PACKAGE_kmod-mt7922-firmware=y
          CONFIG_PACKAGE_kmod-mt7921-common=y
          CONFIG_PACKAGE_kmod-mt7921-firmware=y
          CONFIG_PACKAGE_luci-theme-argon=y

          EOF

          sed -i 's/^[ \t]*//g' ./.config

      - name: Download package source code
        run: |
          make defconfig
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
      - name: Compile firmware
        run: |
          make defconfig
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: R5C
          path: bin/targets
